### ISSUE TITLE
<main> tag required to make webpage well organized

### ISSUE THREAD

**Issue by ehmaddd** [touredri/Portfolio#9]
1. During the process of organizing the webpage into different parts, there is a pivotal role in using the main tag to hold the contents of the main body of the webpage. So if you add the main tag and enclose your main contents into it, it would be a better preview and good for search engine optimization.

2. Somewhere between lines 37-44, there is a small indentation issue which should be resolved to make the code as well organized as the remaining code

**Comment by kalbek** [comment]
- I believe the indentation issues comes when there is unclosed tag 
you should use prettier code formatting VSCode extension.
- Also, for the sake of readability I believe it is important to remove unnecessary white 
spaces on line 45, 47 and 147.

**Comment by Kwaku28** [comment]
I suggest the <a href="https://github.com/touredri/Portfolio/blob/0d8dcc5290b9ca7792c1a6fb87526c01d9180895/index.html#L17">logo<a/> in the header tag should be made a link so when clicked when in any page of the website can be brought back to the homepage.

Thank you 🤝

**Comment by touredri** [comment]
Ok Thank.
I got it

**Comment by touredri** [comment]
Fix
